### ISSUE TITLE
shortcuts work except for next song

### ISSUE THREAD

**Issue by cereal2nd** [lidel/google-music-hotkeys#3] opened 2017-11-27 08:26 UTC
all shortcuts seem to work, except ctrl+shift+0 this one is not responding

**Comment by lidel** [comment] 2017-11-27 08:56
Hi, I was unable to reproduce, need more information from you:

- What is the version of your browser?
- Could you provide URL at which the issue occurs?

**Comment by cereal2nd** [comment] 2017-11-27 09:09
firefox version: 58.0b4 (64-bit)

what do you mean the url?
this is the google play music url: https://play.google.com/music/listen?u=0#/home

Note i also have the containers plugin running

**Comment by lidel** [comment] 2017-11-27 09:22
Thanks, I'll try to replicate it with Firefox Beta later today.

The URL is different depending on which Google Music Page you are on.
For example an album has a dedicated hash so that you can bookmark it.

Are you experiencing the problem for both URLs below? 
- https://play.google.com/music/listen?u=0#/home
- https://play.google.com/music/listen?u=0#/album/Bedelofbqna3m2n4bvti5c2ua4u

**Comment by cereal2nd** [comment] 2017-11-27 09:50
yes i have it on both of the urls

**Comment by lidel** [comment] 2017-11-27 22:14
Did my best, but I was unable to replicate under v58.0b6 with containers plugin. 
Tried on two machines (one Windows, one Linux).

Are you running any other extensions in Firefox? What is your operating system?
I suspect something is hijacking <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>0</kbd> on your machine.

**Comment by lidel** [comment] 2017-12-13 23:42
@Cereal2nd I assume the issue is gone? If not, please reopen with more info.

**Comment by cereal2nd** [comment] 2017-12-14 04:29
No the issue is still there.

**Comment by harpratap** [comment] 2017-12-15 09:11
I'm having the same issue. Firefox 57.0.2 running on Windows 10. Only Ctrl+Shift+0 does not work.

**Comment by lidel** [comment] 2017-12-16 00:08
Ok,  it seems  <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>0</kbd> is hijacked by.. MS Windows (are you both using it?).
The  shortcut lets you switch the input language.

Good news is that you can disable  it, see instructions below:

- https://support.microsoft.com/en-us/help/967893/input-method-editor-keyboard-shortcut-ctrl-shift-0-switches-the-input
- https://www.eightforums.com/general-support/22552-cant-use-ctrl-shift-0-windows-has.html

Let me know if it helped.

**Comment by harpratap** [comment] 2017-12-18 00:38
It works on Firefox and Chrome now, thanks!

**Comment by lidel** [comment] 2017-12-23 12:11
Awesome, glad it helped!

**Comment by lidel** [comment] 2017-12-24 12:56
I am afraid this workaround is not enough. Even tho I've added this information to extension's description at AMO, users are missing it and giving [bad reviews](https://addons.mozilla.org/en-US/firefox/addon/google-music-hotkeys-webext/reviews/) :(

Until #1 is closed we can't customize shortcuts under Firefox. What if we add a second set of shortcuts so that users have at least one working set out-of-the box  in MS Windows? 

* What set of keys would be appropriate as a backup?
* Or maybe just provide a backup alternative for the problematic one (play next)?
Would <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>-</kbd> work?

**Comment by harpratap** [comment] 2017-12-25 00:18
Yes either that or `CTRL` + `SHIFT` + `[`
Both are good choices

**Comment by lidel** [comment] 2017-12-26 14:37
Unfortunately shortcuts with <kbd>[</kbd> are not permitted under Firefox:

> ERROR	Loading extension 'null': Reading manifest: Error processing commands.previous-song-backup.suggested_key.default: Value "Ctrl+Shift+[" must either: match the pattern /^\s*(Alt|Ctrl|Command|MacCtrl)\s*\+\s*(Shift\s*\+\s*)?([A-Z0-9]|Comma|Period|Home|End|PageUp|PageDown|Space|Insert|Delete|Up|Down|Left|Right)\s*$/, match the pattern /^\s*((Alt|Ctrl|Command|MacCtrl)\s*\+\s*)?(Shift\s*\+\s*)?(F[1-9]|F1[0-2])\s*$/, or match the pattern /^(MediaNextTrack|MediaPlayPause|MediaPrevTrack|MediaStop)$/ 

What about <kbd>ALT</kbd>+<kbd>SHIFT</kbd>+<kbd>0</kbd>? Would that work under Windows 10?

**Comment by harpratap** [comment] 2017-12-27 00:42
Sorry, I don't have windows 10 to test this out. Personally, I would prefer `CTRL` + `SHIF` + `-`

**Comment by lidel** [comment] 2017-12-28 18:55
I've released [v1.5.0](https://addons.mozilla.org/en-US/firefox/addon/google-music-hotkeys-webext/versions/?page=1#version-1.5.0) with additional set of shortcuts prefixed with <kbd>Alt</kbd>+<kbd>Shift</kbd>:
- toggle playback: <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>8</kbd> OR <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>8</kbd>, visual hint: <kbd>*</kbd>
- previous song: <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>9</kbd> OR <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>9</kbd>, visual hint: <kbd>(</kbd>
- next song: <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>0</kbd> OR <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>0</kbd>, visual hint: <kbd>)</kbd>

Hopefully this will prove to be flexible enough to work on all platforms until #1 is fixed in Firefox.
Feel free to reopen this issue if none of the above work for you.

**Closed as completed by lidel** 2017-12-28 18:55 UTC

**Comment by lidel** [comment] 2018-05-13 11:51
FYSA just released [v1.6.0](https://github.com/lidel/google-music-hotkeys/releases/tag/v1.6.0) which enables users to customize shortcut keys under Firefox (see https://github.com/lidel/google-music-hotkeys/issues/1#issuecomment-388620900 for more details). 

To make it work I had to do two changes that may impact Windows users:
1. I removed backup set of shortcuts (you can customize original ones, so there is no need for them)
1. I changed the default shortcuts under windows to <kbd>Alt</kbd>+<kbd>Shift</kbd> ones to avoid issue with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>0</kbd> and make it work out-of-the-box for new users. You can always change them anyway, so it should not be a big problem.

I hope this small shakeup will not annoy anyone too much :)
